name: biomagnapro
description: biomagnapro

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http_auth: ^0.3.1
  shared_preferences: ^2.0.4
  webview_flutter: ^1.0.7
  provider: ^4.3.2+2
  flutter_bluetooth_serial: ^0.3.2

  stop_watch_timer: ^1.1.0+1
  scoped_model: ^1.1.0
  assets_audio_player: ^2.0.13+1
  firebase_core: "^1.0.0"
  firebase_auth: "^1.0.0"
  firebase_database: "^6.1.0"
  firebase_storage: "^8.0.0"
  giffy_dialog: ^1.8.0
  cloud_firestore: ^1.0.0
  curved_navigation_bar: ^0.3.4
  firebase_core_platform_interface: ^4.0.0
  meta: ^1.3.0
  carousel_slider: ^3.0.0
  splashscreen: ^1.3.5
  percent_indicator: "^2.1.7+2"





  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: any
  image_picker: ^0.7.2
  meta: ^1.3.0-nullsafety.6
  collection: ^1.15.0
  async: ^2.5.0
  path: ^1.8.0-nullsafety.3
  image_picker_platform_interface: ^2.0.0
  flutter_plugin_android_lifecycle: ^2.0.0
  http: ^0.13.0
  http_parser: ^4.0.0
  typed_data: ^1.3.0
  string_scanner: ^1.1.0
  source_span: ^1.8.0
  term_glyph: ^1.2.0
  charcode: ^1.2.0
  url_launcher: ^6.0.2
  url_launcher_web: ^2.0.0
  url_launcher_windows: ^2.0.0
  url_launcher_macos: ^2.0.0
  url_launcher_linux: ^2.0.0
  js: 0.6.3-nullsafety.3
  permission_handler: ^6.1.1
  shared_preferences: ^2.0.4
  autocomplete_textfield: ^1.7.3
  animated_text_kit: ^4.1.0
  table_calendar: ^2.3.3
  characters: ^1.1.0
  shared_preferences_windows: ^2.0.0
  path_provider_windows: ^2.0.0
  ffi: ^1.0.0
  path_provider_platform_interface: ^2.0.0
  shared_preferences_platform_interface: ^2.0.0
  shared_preferences_web: ^2.0.0
  shared_preferences_macos: ^2.0.0
  shared_preferences_linux: ^2.0.0
  path_provider_linux: ^2.0.0
  permission_handler_platform_interface: ^3.1.1
  win32: ^2.0.0
  stop_watch_timer: ^1.1.0+1
  rxdart: ^0.25.0
  flutter_bluetooth_serial: ^0.3.2

  uuid: ^2.2.2
  convert: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/fond.png
    - assets/girl.png
    - assets/aux1.png
    - assets/logfond.jpeg
    - assets/log.png
    - assets/paypal.png
    - assets/logoblanco.png
    - assets/fondo.png
    - assets/person.png
    - assets/fondo2.png
    - assets/fondo3.png
    - assets/fumar.png
    - assets/alcohol.png
    - assets/droga.png
    - assets/battery.png
    - assets/firmware.png
    - assets/phone.png
    - assets/label.png
    - assets/page1.png
    - assets/page2.png
    - assets/page3.png
    - assets/page4.png
    - assets/splash.png
    - assets/play.png
    - assets/pause.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
